parameters:
  - name: targetRegion
    type: string
    default: ""
  - name: bakeTimeInMinutes
    type: number
    default: 0
  - name: dynatraceSmokeTest
    type: boolean
    default: false

stages:
  - ${{ if eq(parameters.dynatraceSmokeTest, true) }}:
      - template: ../common/bake-time.yml
        parameters:
          targetRegion: ${{ parameters.targetRegion }}
          bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutes }}
          dependsOnStages:
            - release_${{ parameters.targetRegion }}
            - deploy_validation_${{ parameters.targetRegion }}
  - ${{ else }}:
      - template: ../common/bake-time.yml
        parameters:
          targetRegion: ${{ parameters.targetRegion }}
          bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutes }}
          dependsOnStages:
            - release_${{ parameters.targetRegion }}
