parameters:
  - name: targetRegion
    type: string
    default: ""
  - name: bakeTimeInMinutes
    type: number
    default: 0
  - name: skipBakeTime
    type: boolean
    default: false
  - name: skipPostDeployValidation
    type: boolean
    default: false

stages:
  - ${{ if eq(parameters.skipPostDeployValidation, true) }}:
      - template: ../common/bake-time.yml
        parameters:
          targetRegion: ${{ parameters.targetRegion }}
          bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutes }}
          dependsOnStages:
            - release_${{ parameters.targetRegion }}
            - release_${{ parameters.targetRegion }} # Workaround to simulate a post deploy validation stage that does not exist
  - ${{ else }}:
      - template: ../common/bake-time.yml
        parameters:
          targetRegion: ${{ parameters.targetRegion }}
          bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutes }}
          dependsOnStages:
            - release_${{ parameters.targetRegion }}
            - post_deploy_validation_${{ parameters.targetRegion }}
