parameters:
  - name: targetRegion
    type: string
    default: ""
  - name: skipPostDeployValidation
    type: boolean
    default: false

stages:
  - template: ../common/post-deploy-validation.yml
    parameters:
      targetRegion: ${{ parameters.targetRegion }}
      skipPostDeployValidation: ${{ parameters.skipPostDeployValidation }}
      dependsOnStages:
        - init
        - release_${{ parameters.targetRegion }}
