parameters:
  - name: targetRegion
    type: string
    default: ""
  - name: previousRegion
    type: string
    default: ""
  - name: autoPromote
    type: boolean
    default: false
  - name: skipStage
    type: boolean
    default: false

stages:
  - ${{ if eq(parameters.previousRegion, 'none') }}:
      - template: ../common/promote.yml
        parameters:
          previousRegion: ${{ parameters.previousRegion }}
          targetRegion: ${{ parameters.targetRegion }}
          autoPromote: ${{ parameters.autoPromote }}
          skipStage: ${{ parameters.skipStage }}
          dependsOnStages:
            - init
  - ${{ else }}:
      - template: ../common/promote.yml
        parameters:
          previousRegion: ${{ parameters.previousRegion }}
          targetRegion: ${{ parameters.targetRegion }}
          autoPromote: ${{ parameters.autoPromote }}
          skipStage: ${{ parameters.skipStage }}
          dependsOnStages:
            - init
            - bake_time_${{ parameters.previousRegion }}
