parameters:
  - name: teamIdentifier
    type: string
    default: ""
  - name: appName
    type: string
    default: ""
  - name: artifactVersion
    type: string
    default: ""
  - name: rings
    type: object
    default: []
  # - name: originBranch   <<<<<<<< if needed: RETRIEVE it from env var and add to variables refer to GH_APP_REPO_URL
  #   type: string
  #   default: ""

variables:
  TORREMO_LIB_CACHE_FOLDER: $(Pipeline.Workspace)/s/torremo-lib-cache
  TEAM_IDENTIFIER: ${{ parameters.teamIdentifier }}
  APP_NAME: ${{ parameters.appName }}
  ARTIFACT_VERSION: ${{ parameters.artifactVersion }}
  GH_APP_REPO_URL: $(Build.Repository.Uri)
  GH_GITOPS_REPO_URL: "https://github.tools.sap/concur-sap-ecosystem/workloads"

stages:
  - template: /stages/init.yml
    parameters:
      rings: ${{ parameters.rings }}

  - ${{ each ring in parameters.rings }}:
      # promote
      - template: /stages/ring/promote.yml
        parameters:
          targetRegion: ${{ ring.targetRegion }}
          previousRegion: ${{ ring.previousRegion }}
          autoPromote: ${{ ring.autoPromote }}
      # release
      - template: /stages/ring/release.yml
        parameters:
          targetRegion: ${{ ring.targetRegion }}
      # post deploy validation
      - template: /stages/ring/post-deploy-validation.yml
        parameters:
          targetRegion: ${{ ring.targetRegion }}
          skipPostDeployValidation: ${{ ring.skipPostDeployValidation }}
      # bake time
      - template: /stages/ring/bake-time.yml
        parameters:
          targetRegion: ${{ ring.targetRegion }}
          bakeTimeInMinutes: ${{ ring.bakeTimeInMinutes }}
          skipBakeTime: ${{ ring.skipBakeTime }}
          skipPostDeployValidation: ${{ ring.skipPostDeployValidation }}
