parameters:
  - name: teamIdentifier
    type: string
    default: ""
  - name: appName
    type: string
    default: ""
  - name: artifactVersion
    type: string
    default: ""
  - name: rings
    type: object
    default:
      - name: "ring_0"
        skip: false
        autoPromote: false
        dynatraceSmokeTest: false
        targetRegion: ""
        previousRegion: ""
        bakeTimeInMinutes: 0
      - name: "ring_1"
        skip: true
        autoPromote: false
        dynatraceSmokeTest: false
        targetRegion: ""
        previousRegion: ""
        bakeTimeInMinutes: 0
      - name: "ring_2"
        skip: true
        autoPromote: false
        dynatraceSmokeTest: false
        targetRegion: ""
        previousRegion: ""
        bakeTimeInMinutes: 0
      - name: "ring_3"
        skip: true
        autoPromote: false
        dynatraceSmokeTest: false
        targetRegion: ""
        previousRegion: ""
        bakeTimeInMinutes: 0
  # - name: originBranch   <<<<<<<< if needed: RETRIEVE it from env var and add to variables refer to GH_APP_REPO_URL
  #   type: string
  #   default: ""

variables:
  TORREMO_LIB_CACHE_FOLDER: $(Pipeline.Workspace)/s/torremo-lib-cache
  TEAM_IDENTIFIER: ${{ parameters.teamIdentifier }}
  APP_NAME: ${{ parameters.appName }}
  ARTIFACT_VERSION: ${{ parameters.artifactVersion }}
  GH_APP_REPO_URL: $(Build.Repository.Uri)
  GH_GITOPS_REPO_URL: "https://github.tools.sap/concur-sap-ecosystem/workloads"

stages:
  - template: /stages/init.yml

  - ${{ each ring in parameters.rings }}:
      - template: /stages/ring/promote.yml
        parameters:
          skipStage: ${{ ring.skip }}
          autoPromote: ${{ ring.autoPromote }}
          targetRegion: ${{ ring.targetRegion }}
          previousRegion: ${{ ring.previousRegion }}
      - template: /stages/ring/release.yml
        parameters:
          targetRegion: ${{ ring.targetRegion }}
      - template: /stages/ring/deploy-validation.yml
        parameters:
          dynatraceSmokeTest: ${{ ring.dynatraceSmokeTest }}
          targetRegion: ${{ ring.targetRegion }}
      - template: /stages/ring/bake-time.yml
        parameters:
          bakeTimeInMinutes: ${{ ring.bakeTimeInMinutes }}
          dynatraceSmokeTest: ${{ ring.dynatraceSmokeTest }}
          targetRegion: ${{ ring.targetRegion }}
