parameters:
  - name: teamIdentifier
    type: string
    default: ""
  - name: appName
    type: string
    default: ""
  - name: artifactVersion
    type: string
    default: ""
  - name: skipRing0ReleaseStage
    type: boolean
    default: false
  - name: targetRegionRing0
    type: string
    default: ""
  - name: bakeTimeInMinutesRing0ReleaseStage
    type: number
    default: 0
  - name: skipRing1ReleaseStage
    type: boolean
    default: false
  - name: targetRegionRing1
    type: string
    default: ""
  - name: bakeTimeInMinutesRing1ReleaseStage
    type: number
    default: 0
  - name: skipRing2ReleaseStage
    type: boolean
    default: false
  - name: targetRegionRing2
    type: string
    default: ""
  - name: bakeTimeInMinutesRing2ReleaseStage
    type: number
    default: 0
  - name: skipRing3ReleaseStage
    type: boolean
    default: false
  - name: targetRegionRing3
    type: string
    default: ""

variables:
  TORREMO_LIB_CACHE_FOLDER: $(Pipeline.Workspace)/s/torremo-lib-cache
  TEAM_IDENTIFIER: ${{ parameters.teamIdentifier }}
  APP_NAME: ${{ parameters.appName }}
  ARTIFACT_VERSION: ${{ parameters.artifactVersion }}
  GH_APP_REPO_URL: $(Build.Repository.Uri)
  GH_GITOPS_REPO_URL: "https://github.tools.sap/concur-sap-ecosystem/workloads"

stages:
  - template: /stages/init.yml
  # Ring 0
  - template: /stages/release-ring-0.yml
    parameters:
      skipStage: ${{ parameters.skipRing0ReleaseStage }}
      targetRegion: ${{ parameters.targetRegionRing0 }}
  # - template: /stages/condition-deploy-status-ring-0.yml
  #   parameters:
  #     targetRegion: ${{ parameters.targetRegionRing0 }}
  # - template: /stages/bake-time-ring-0.yml
  #   parameters:
  #     bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutesRing0ReleaseStage }}
  #     targetRegion: ${{ parameters.targetRegionRing0 }}
  # # Ring 1
  # - template: /stages/release-ring-1.yml
  #   parameters:
  #     skipStage: ${{ parameters.skipRing1ReleaseStage }}
  #     targetRegion: ${{ parameters.targetRegionRing1 }}
  # - template: /stages/condition-deploy-status-ring-1.yml
  #   parameters:
  #     targetRegion: ${{ parameters.targetRegionRing1 }}
  # - template: /stages/bake-time-ring-1.yml
  #   parameters:
  #     bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutesRing1ReleaseStage }}
  #     targetRegion: ${{ parameters.targetRegionRing1 }}
  # # Ring 2
  # - template: /stages/release-ring-2.yml
  #   parameters:
  #     skipStage: ${{ parameters.skipRing2ReleaseStage }}
  #     targetRegion: ${{ parameters.targetRegionRing2 }}
  # - template: /stages/condition-deploy-status-ring-2.yml
  #   parameters:
  #     targetRegion: ${{ parameters.targetRegionRing2 }}
  # - template: /stages/bake-time-ring-2.yml
  #   parameters:
  #     bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutesRing2ReleaseStage }}
  #     targetRegion: ${{ parameters.targetRegionRing2 }}
  # # Ring 3
  # - template: /stages/release-ring-3.yml
  #   parameters:
  #     skipStage: ${{ parameters.skipRing3ReleaseStage }}
  #     targetRegion: ${{ parameters.targetRegionRing3 }}
  # - template: /stages/condition-deploy-status-ring-3.yml
  #   parameters:
  #     targetRegion: ${{ parameters.targetRegionRing3 }}
