parameters:
  - name: teamIdentifier
    type: string
    default: ""
  - name: appName
    type: string
    default: ""
  - name: artifactVersion
    type: string
    default: ""
  - name: skipRing0
    type: boolean
    default: false
  - name: autoPromoteRing0
    type: boolean
    default: false
  - name: dynatraceSmokeTestRing0
    type: boolean
    default: false
  - name: targetRegionRing0
    type: string
    default: ""
  - name: bakeTimeInMinutesRing0
    type: number
    default: 0
  - name: skipRing1
    type: boolean
    default: true
  - name: autoPromoteRing1
    type: boolean
    default: false
  - name: dynatraceSmokeTestRing1
    type: boolean
    default: false
  - name: targetRegionRing1
    type: string
    default: ""
  - name: bakeTimeInMinutesRing1
    type: number
    default: 0
  - name: skipRing2
    type: boolean
    default: true
  - name: autoPromoteRing2
    type: boolean
    default: false
  - name: dynatraceSmokeTestRing2
    type: boolean
    default: false
  - name: targetRegionRing2
    type: string
    default: ""
  - name: bakeTimeInMinutesRing2
    type: number
    default: 0
  - name: skipRing3
    type: boolean
    default: true
  - name: autoPromoteRing3
    type: boolean
    default: false
  - name: dynatraceSmokeTestRing3
    type: boolean
    default: false
  - name: targetRegionRing3
    type: string
    default: ""
  - name: dynatraceSmokeTest
    type: boolean
    default: false
  # - name: originBranch   <<<<<<<< if needed: RETRIEVE it from env var and add to variables refer to GH_APP_REPO_URL
  #   type: string
  #   default: ""

variables:
  TORREMO_LIB_CACHE_FOLDER: $(Pipeline.Workspace)/s/torremo-lib-cache
  TEAM_IDENTIFIER: ${{ parameters.teamIdentifier }}
  APP_NAME: ${{ parameters.appName }}
  ARTIFACT_VERSION: ${{ parameters.artifactVersion }}
  GH_APP_REPO_URL: $(Build.Repository.Uri)
  GH_GITOPS_REPO_URL: "https://github.tools.sap/concur-sap-ecosystem/workloads"

stages:
  # Init
  - template: /stages/init.yml
  # Ring 0
  - template: /stages/ring-0/promote.yml
    parameters:
      skipStage: ${{ parameters.skipRing0 }}
      autoPromote: ${{ parameters.autoPromoteRing0 }}
      targetRegion: ${{ parameters.targetRegionRing0 }}
  - template: /stages/ring-0/release.yml
    parameters:
      targetRegion: ${{ parameters.targetRegionRing0 }}
  - template: /stages/ring-0/deploy-validation.yml
    parameters:
      dynatraceSmokeTest: ${{ parameters.dynatraceSmokeTestRing0 }}
      targetRegion: ${{ parameters.targetRegionRing0 }}
  - template: /stages/ring-0/bake-time.yml
    parameters:
      bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutesRing0 }}
      targetRegion: ${{ parameters.targetRegionRing0 }}
  # Ring 1
  - template: /stages/ring-1/promote.yml
    parameters:
      skipStage: ${{ parameters.skipRing1 }}
      autoPromote: ${{ parameters.autoPromoteRing1 }}
      previousRegion: ${{ parameters.targetRegionRing0 }}
      targetRegion: ${{ parameters.targetRegionRing1 }}
  - template: /stages/ring-1/release.yml
    parameters:
      targetRegion: ${{ parameters.targetRegionRing1 }}
  - template: /stages/ring-1/deploy-validation.yml
    parameters:
      dynatraceSmokeTest: ${{ parameters.dynatraceSmokeTestRing1 }}
      targetRegion: ${{ parameters.targetRegionRing1 }}
  - template: /stages/ring-1/bake-time.yml
    parameters:
      bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutesRing1 }}
      targetRegion: ${{ parameters.targetRegionRing1 }}
  # Ring 2
  - template: /stages/ring-2/promote.yml
    parameters:
      skipStage: ${{ parameters.skipRing2 }}
      autoPromote: ${{ parameters.autoPromoteRing2 }}
      previousRegion: ${{ parameters.targetRegionRing1 }}
      targetRegion: ${{ parameters.targetRegionRing2 }}
  - template: /stages/ring-2/release.yml
    parameters:
      targetRegion: ${{ parameters.targetRegionRing2 }}
  - template: /stages/ring-2/deploy-validation.yml
    parameters:
      dynatraceSmokeTest: ${{ parameters.dynatraceSmokeTestRing2 }}
      targetRegion: ${{ parameters.targetRegionRing2 }}
  - template: /stages/ring-2/bake-time.yml
    parameters:
      bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutesRing2 }}
      targetRegion: ${{ parameters.targetRegionRing2 }}
  # Ring 3
  - template: /stages/ring-3/promote.yml
    parameters:
      skipStage: ${{ parameters.skipRing3 }}
      autoPromote: ${{ parameters.autoPromoteRing3 }}
      previousRegion: ${{ parameters.targetRegionRing2 }}
      targetRegion: ${{ parameters.targetRegionRing3 }}
  - template: /stages/ring-3/release.yml
    parameters:
      targetRegion: ${{ parameters.targetRegionRing3 }}
  - template: /stages/ring-3/deploy-validation.yml
    parameters:
      dynatraceSmokeTest: ${{ parameters.dynatraceSmokeTestRing3 }}
      targetRegion: ${{ parameters.targetRegionRing3 }}
