parameters:
  - name: teamIdentifier
    type: string
    default: ""
  - name: appName
    type: string
    default: ""
  - name: artifactVersion
    type: string
    default: ""
  - name: ghRepoUri
    type: string
    default: ""
  - name: skipRing0ReleaseStage
    type: boolean
    default: false
  - name: targetRegionRing0
    type: string
    default: ""
  - name: skipRing1ReleaseStage
    type: boolean
    default: false
  - name: targetRegionRing1
    type: string
    default: ""
  - name: bakeTimeInMinutesRing1ReleaseStage
    type: number
    default: 0
  - name: skipRing2ReleaseStage
    type: boolean
    default: false
  - name: targetRegionRing2
    type: string
    default: ""
  - name: bakeTimeInMinutesRing2ReleaseStage
    type: number
    default: 0
  - name: skipRing3ReleaseStage
    type: boolean
    default: false
  - name: targetRegionRing3
    type: string
    default: ""
  - name: bakeTimeInMinutesRing3ReleaseStage
    type: number
    default: 0

variables:
  TORREMO_LIB_CACHE_FOLDER: $(Pipeline.Workspace)/s/torremo-lib-cache

stages:
  - template: /stages/init.yml
    parameters:
      teamIdentifier: ${{ parameters.teamIdentifier }}
      appName: ${{ parameters.appName }}
      artifactVersion: ${{ parameters.artifactVersion }}
  # Ring 0
  - template: /stages/release-ring-0.yml
    parameters:
      skipStage: ${{ parameters.skipRing0ReleaseStage }}
      teamIdentifier: ${{ parameters.teamIdentifier }}
      appName: ${{ parameters.appName }}
      artifactVersion: ${{ parameters.artifactVersion }}
      targetRegion: ${{ parameters.targetRegionRing0 }}
      ghRepoUri: ${{ parameters.ghRepoUri }}
  - template: /stages/condition-deploy-status-ring-0.yml
    parameters:
      teamIdentifier: ${{ parameters.teamIdentifier }}
      appName: ${{ parameters.appName }}
      artifactVersion: ${{ parameters.artifactVersion }}
      targetRegion: ${{ parameters.targetRegionRing0 }}
      ghRepoUri: ${{ parameters.ghRepoUri }}
  # # Ring 1
  # - template: /stages/bake-time-ring-1.yml
  #   parameters:
  #     skipStage: ${{ parameters.skipRing1ReleaseStage }}
  #     bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutesRing1ReleaseStage }}
  #     targetRegion: ${{ parameters.targetRegionRing1 }}
  # - template: /stages/release-ring-1.yml
  #   parameters:
  #     teamIdentifier: ${{ parameters.teamIdentifier }}
  #     appName: ${{ parameters.appName }}
  #     artifactVersion: ${{ parameters.artifactVersion }}
  #     targetRegion: ${{ parameters.targetRegionRing1 }}
  #     ghRepoUri: ${{ parameters.ghRepoUri }}
  # - template: /stages/condition-deploy-status-ring-1.yml
  #   parameters:
  #     teamIdentifier: ${{ parameters.teamIdentifier }}
  #     appName: ${{ parameters.appName }}
  #     artifactVersion: ${{ parameters.artifactVersion }}
  #     targetRegion: ${{ parameters.targetRegionRing1 }}
  #     ghRepoUri: ${{ parameters.ghRepoUri }}
  # # Ring 2
  # - template: /stages/bake-time-ring-2.yml
  #   parameters:
  #     skipStage: ${{ parameters.skipRing2ReleaseStage }}
  #     bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutesRing2ReleaseStage }}
  #     targetRegion: ${{ parameters.targetRegionRing2 }}
  # - template: /stages/release-ring-2.yml
  #   parameters:
  #     teamIdentifier: ${{ parameters.teamIdentifier }}
  #     appName: ${{ parameters.appName }}
  #     artifactVersion: ${{ parameters.artifactVersion }}
  #     targetRegion: ${{ parameters.targetRegionRing2 }}
  #     ghRepoUri: ${{ parameters.ghRepoUri }}
  # - template: /stages/condition-deploy-status-ring-2.yml
  #   parameters:
  #     teamIdentifier: ${{ parameters.teamIdentifier }}
  #     appName: ${{ parameters.appName }}
  #     artifactVersion: ${{ parameters.artifactVersion }}
  #     targetRegion: ${{ parameters.targetRegionRing2 }}
  #     ghRepoUri: ${{ parameters.ghRepoUri }}
  # # Ring 3
  # - template: /stages/bake-time-ring-3.yml
  #   parameters:
  #     skipStage: ${{ parameters.skipRing3ReleaseStage }}
  #     bakeTimeInMinutes: ${{ parameters.bakeTimeInMinutesRing3ReleaseStage }}
  #     targetRegion: ${{ parameters.targetRegionRing3 }}
  # - template: /stages/release-ring-3.yml
  #   parameters:
  #     teamIdentifier: ${{ parameters.teamIdentifier }}
  #     appName: ${{ parameters.appName }}
  #     artifactVersion: ${{ parameters.artifactVersion }}
  #     targetRegion: ${{ parameters.targetRegionRing3 }}
  #     ghRepoUri: ${{ parameters.ghRepoUri }}
  # - template: /stages/condition-deploy-status-ring-3.yml
  #   parameters:
  #     teamIdentifier: ${{ parameters.teamIdentifier }}
  #     appName: ${{ parameters.appName }}
  #     artifactVersion: ${{ parameters.artifactVersion }}
  #     targetRegion: ${{ parameters.targetRegionRing3 }}
  #     ghRepoUri: ${{ parameters.ghRepoUri }}
