parameters:
  - name: targetRegion
    type: string
    default: ""
  - name: autoPromote
    type: boolean
    default: false
  - name: skipStage
    type: boolean
    default: false
  - name: previousRegion
    type: string
    default: "none"

stages:
  - template: ../common/promote.yml
    parameters:
      previousRegion: ${{ parameters.previousRegion }}
      targetRegion: ${{ parameters.targetRegion }}
      autoPromote: ${{ parameters.autoPromote }}
      skipStage: ${{ parameters.skipStage }}
      dependsOnStages:
        - init
