parameters:
  - name: targetRegion
    type: string
    default: ""

stages:
  - template: ../common/release.yml
    parameters:
      targetRegion: ${{ parameters.targetRegion }}
      dependsOnStages:
        - init
        - promote_${{ parameters.targetRegion }}
