# release-integration.yml
parameters:
  - name: teamIdentifier
    type: string
    default: ""
  - name: appName
    type: string
    default: ""
  - name: targetRegion
    type: string
    default: ""
  - name: artifactVersion
    type: string
    default: ""
  - name: ghRepoUri
    type: string
    default: ""

stages:
  - stage: condition_deploy_status_ring_0
    displayName: 🩺 Release Health Check for ${{ parameters.targetRegion }} Environment
    dependsOn: ["release_ring_0"]
    condition: |
      and(
        eq(dependencies.release_ring_0.result, 'Succeeded'),
        ne('${{ parameters.targetRegion }}', ''),
        ne('${{ parameters.teamIdentifier }}', ''),
        ne('${{ parameters.appName }}', ''),
        ne('${{ parameters.artifactVersion }}', ''),
        ne('${{ parameters.ghRepoUri }}', '')
      )
    pool:
      name: "Azure Pipelines"
      vmImage: "ubuntu-latest"
    jobs:
      - job: Argo_Application_Health_Check
        steps:
          - checkout: self
          - bash: |
              script_content=$(curl -sL -H "Authorization: token $(GH_TOKEN)" \
                "https://github.com/api/v3/repos/manganellidev/custom-sdp-pipeline-azure/contents/scripts/condition-deploy-status.sh" | \
                jq -r .content | base64 -d)

              if [[ -z "$script_content" ]]; then
                echo "Error: Failed to retrieve script content."
                exit 1
              fi

              appName="${{ parameters.appName }}"
              artifactVersion="${{ parameters.artifactVersion }}"
              targetRegion="${{ parameters.targetRegion }}"
              teamIdentifier="${{ parameters.teamIdentifier }}"
              ghRepoUri="${{ parameters.ghRepoUri }}"

              echo "$script_content" | bash -s -- "$appName" "$artifactVersion" "$targetRegion" "$teamIdentifier" "$ghRepoUri"
            displayName: "Argo Application Health Check"
      - job: Dynatrace_Synthetic_Monitor_Smoke_Test
        steps:
          - checkout: self
          - bash: |
              script_content=$(curl -sL -H "Authorization: token $(GH_TOKEN)" \
                "https://github.com/api/v3/repos/manganellidev/custom-sdp-pipeline-azure/contents/scripts/smoke-tests.sh" | \
                jq -r .content | base64 -d)

              if [[ -z "$script_content" ]]; then
                echo "Error: Failed to retrieve script content."
                exit 1
              fi

              appName="${{ parameters.appName }}"
              artifactVersion="${{ parameters.artifactVersion }}"
              targetRegion="${{ parameters.targetRegion }}"
              teamIdentifier="${{ parameters.teamIdentifier }}"
              ghRepoUri="${{ parameters.ghRepoUri }}"

              echo "$script_content" | bash -s -- "$appName" "$artifactVersion" "$targetRegion" "$teamIdentifier" "$ghRepoUri"
            displayName: "Dynatrace Synthetic Monitor Smoke Test"
