parameters:
  - name: targetRegion
    type: string
    default: ""

stages:
  - stage: condition_deploy_status_ring_0
    displayName: 🩺 Release Health Check for ${{ parameters.targetRegion }} Environment
    dependsOn: ["init", "release_ring_0"]
    condition: |
      and(
        eq(dependencies.release_ring_0.result, 'Succeeded'),
        ne('${{ parameters.targetRegion }}', '')
      )
    pool:
      name: "Azure Pipelines"
      vmImage: "ubuntu-latest"
    jobs:
      - job: argo_application_health_check
        displayName: "Argo Application Health Check"
        checkout: none
        variables:
          TORREMO_LIB_LATEST_VERSION: $[ stageDependencies.init.download_cache_torremo_library.outputs['fetch_latest_release_tag.LATEST_VERSION'] ]
        steps:
          - task: Cache@2
            displayName: "Cache Torremo Library"
            inputs:
              key: '"torremo" | "$(Agent.OS)" | "$(TORREMO_LIB_LATEST_VERSION)"'
              path: "$(TORREMO_LIB_CACHE_FOLDER)/"

          - task: torremo-beta@1.0.41
            displayName: validateDeploy
            inputs:
              stepName: "validateDeploy"

      - job: dynatrace_synthetic_monitor_smoke_test
        displayName: "Dynatrace Synthetic Monitor Smoke Test"
        dependsOn: argo_application_health_check
        checkout: none
        variables:
          TORREMO_LIB_LATEST_VERSION: $[ stageDependencies.init.download_cache_torremo_library.outputs['fetch_latest_release_tag.LATEST_VERSION'] ]
        steps:
          - task: Cache@2
            displayName: "Cache Torremo Library"
            inputs:
              key: '"torremo" | "$(Agent.OS)" | "$(TORREMO_LIB_LATEST_VERSION)"'
              path: "$(TORREMO_LIB_CACHE_FOLDER)/"

          - task: torremo-beta@1.0.41
            displayName: validateDeploy
            inputs:
              stepName: "validateDeploy"
