parameters:
  - name: targetRegion
    type: string
    default: ""

stages:
  - stage: condition_deploy_status_ring_2
    displayName: 🩺 Condition Deploy Status for ${{ parameters.targetRegion }}
    dependsOn: ["init", "release_ring_2"]
    condition: |
      and(
        eq(dependencies.release_ring_2.result, 'Succeeded'),
        ne('${{ parameters.targetRegion }}', '')
      )
    pool:
      name: "Azure Pipelines"
      vmImage: "ubuntu-latest"
    jobs:
      - job: release
        steps:
          - checkout: self
          - bash: |
              script_content=$(curl -sL -H "Authorization: token $(GH_TOKEN)" \
                "https://github.com/api/v3/repos/manganellidev/custom-sdp-pipeline-azure/contents/scripts/condition-deploy-status.sh" | \
                jq -r .content | base64 -d)

              if [[ -z "$script_content" ]]; then
                echo "Error: Failed to retrieve script content."
                exit 1
              fi

              appName="${{ parameters.appName }}"
              artifactVersion="${{ parameters.artifactVersion }}"
              targetRegion="${{ parameters.targetRegion }}"
              teamIdentifier="${{ parameters.teamIdentifier }}"
              ghRepoUri="${{ parameters.ghRepoUri }}"

              echo "$script_content" | bash -s -- "$appName" "$artifactVersion" "$targetRegion" "$teamIdentifier" "$ghRepoUri"
            displayName: "Condition Deploy Status"
