parameters:
  - name: targetRegion
    type: string
    default: ""
  - name: skipStage
    type: boolean
    default: false

stages:
  - stage: release_ring_3
    displayName: 🚀 Release ${{ parameters.targetRegion }} Environment
    dependsOn:
      [
        "init",
        "release_ring_2",
        "condition_deploy_status_ring_2",
        "bake_time_release_ring_2",
      ]
    condition: |
      and(
        eq(dependencies.release_ring_2.result, 'Succeeded'),
        eq(dependencies.condition_deploy_status_ring_2.result, 'Succeeded'),
        eq(dependencies.bake_time_release_ring_2.result, 'Succeeded'),
        eq('${{ parameters.skipStage }}', 'false'),
        ne('${{ parameters.targetRegion }}', '')
      )
    pool:
      name: "Azure Pipelines"
      vmImage: "ubuntu-latest"
    jobs:
      - job: gitops_deploy
        displayName: "GitOps Deploy"
        variables:
          TORREMO_LIB_LATEST_VERSION: $[ stageDependencies.init.download_cache_torremo_library.outputs['fetch_latest_release_tag.LATEST_VERSION'] ]
        steps:
          - checkout: none
          - task: Cache@2
            displayName: "Cache Torremo Library"
            inputs:
              key: '"torremo" | "$(Agent.OS)" | "$(TORREMO_LIB_LATEST_VERSION)"'
              path: "$(TORREMO_LIB_CACHE_FOLDER)/"

          - task: torremo-beta@1
            displayName: GitOps
            env:
              GH_TOKEN: $(GH_TOKEN)
            inputs:
              stepName: "gitops"
              flags: >
                --teamIdentifier $(TEAM_IDENTIFIER)
                --appName $(APP_NAME)
                --artifactVersion $(ARTIFACT_VERSION)
                --targetRegion ${{ parameters.targetRegion }}
                --githubAppRepoToken $(GH_TOKEN)
                --githubAppRepoUrl $(GH_APP_REPO_URL)
                --githubGitOpsRepoToken $(GH_TOKEN)
                --githubGitOpsRepoUrl $(GH_GITOPS_REPO_URL)
