parameters:
  - name: targetRegion
    type: string
    default: ""
  - name: skipStage
    type: boolean
    default: false

stages:
  - stage: release_ring_0
    displayName: 🚀 Release ${{ parameters.targetRegion }} Environment
    dependsOn: ["init"]
    condition: |
      and(
        eq(dependencies.init.result, 'Succeeded'),
        eq('${{ parameters.skipStage }}', 'false'),
        ne('${{ parameters.targetRegion }}', '')
      )
    pool:
      name: "Azure Pipelines"
      vmImage: "ubuntu-latest"
    jobs:
      - job: gitops_deploy
        displayName: "GitOps Deploy"
        variables:
          TORREMO_LIB_LATEST_VERSION: $[ stageDependencies.init.download_cache_torremo_library.outputs['fetch_latest_release_tag.LATEST_VERSION'] ]
        steps:
          - task: Cache@2
            displayName: "Cache Torremo Library"
            inputs:
              key: '"torremo" | "$(Agent.OS)" | "$(TORREMO_LIB_LATEST_VERSION)"'
              path: "$(TORREMO_LIB_CACHE_FOLDER)/"

          - task: torremo-beta@1.0.41
            displayName: GitOps
            inputs:
              stepName: "gitops"
              gitHubConnection: ""
              # flags: "--teamIdentifier $(TEAM_IDENTIFIER) --appName $(APP_NAME) --artifactVersion $(ARTIFACT_VERSION)"
