# release-integration.yml
parameters:
  - name: teamIdentifier
    type: string
    default: ""
  - name: appName
    type: string
    default: ""
  - name: targetRegion
    type: string
    default: ""
  - name: artifactVersion
    type: string
    default: ""
  - name: ghRepoUri
    type: string
    default: ""
  - name: skipStage
    type: boolean
    default: false

stages:
  - stage: release_ring_0
    displayName: 🚀 Release ${{ parameters.targetRegion }} Environment
    dependsOn: ["init"]
    condition: |
      and(
        eq(dependencies.init.result, 'Succeeded'),
        eq('${{ parameters.skipStage }}', 'false'),
        ne('${{ parameters.targetRegion }}', ''),
        ne('${{ parameters.teamIdentifier }}', ''),
        ne('${{ parameters.appName }}', ''),
        ne('${{ parameters.artifactVersion }}', ''),
        ne('${{ parameters.ghRepoUri }}', '')
      )
    pool:
      name: "Azure Pipelines"
      vmImage: "ubuntu-latest"
    jobs:
      - job: gitops_deploy
        displayName: "GitOps Deploy"
        variables:
          TORREMO_LIB_LATEST_VERSION: $[ stageDependencies.init.download_cache_torremo_library.outputs['fetch_latest_release_tag.LATEST_VERSION'] ]
          TEAM_IDENTIFIER: $[ stageDependencies.init.export_sdp_params.outputs['export_sdp_params.TEAM_IDENTIFIER'] ]
          APP_NAME: $[ stageDependencies.init.export_sdp_params.outputs['export_sdp_params.APP_NAME'] ]
          ARTIFACT_VERSION: $[ stageDependencies.init.export_sdp_params.outputs['export_sdp_params.ARTIFACT_VERSION'] ]
        steps:
          - task: Cache@2
            displayName: "Cache Torremo Library"
            inputs:
              key: '"torremo" | "$(Agent.OS)" | "$(TORREMO_LIB_LATEST_VERSION)"'
              path: "$(TORREMO_LIB_CACHE_FOLDER)/"

          - bash: |
              echo "Calling Set Config File ..."
              echo "$(TEAM_IDENTIFIER)"
              echo "$(APP_NAME)"
              echo "$(ARTIFACT_VERSION)"
            displayName: "Set Config File"

          - bash: |
              echo "Calling Deploy ..."
            displayName: "Deploy"
