# release-integration.yml
parameters:
  - name: teamIdentifier
    type: string
    default: ""
  - name: appName
    type: string
    default: ""
  - name: targetRegion
    type: string
    default: ""
  - name: artifactVersion
    type: string
    default: ""
  - name: ghRepoUri
    type: string
    default: ""
  - name: skipStage
    type: boolean
    default: false

stages:
  - stage: release_ring_0
    displayName: 🚀 Release ${{ parameters.targetRegion }} Environment
    dependsOn: ["init"]
    condition: |
      and(
        eq(dependencies.init.result, 'Succeeded'),
        eq('${{ parameters.skipStage }}', 'false'),
        ne('${{ parameters.targetRegion }}', ''),
        ne('${{ parameters.teamIdentifier }}', ''),
        ne('${{ parameters.appName }}', ''),
        ne('${{ parameters.artifactVersion }}', ''),
        ne('${{ parameters.ghRepoUri }}', '')
      )
    pool:
      name: "Azure Pipelines"
      vmImage: "ubuntu-latest"
    jobs:
      - job: Cache_Torremo_library
        variables:
          LATEST_VERSION: $[ dependencies.init.outputs['fetchLatestReleaseTag.LATEST_VERSION'] ]
        steps:
          - task: Cache@2
            displayName: "Cache Torremo Library"
            inputs:
              key: '"torremo" | "$(Agent.OS)" | "$(LATEST_VERSION)"'
              path: "$(TORREMO_LIB_CACHE_FOLDER)/"

      - job: Gitops_Deploy
        dependsOn: Cache_Torremo_library
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                echo "Listing contents of tmp directory:"
                ls -la $(TORREMO_LIB_CACHE_FOLDER)/

          - bash: |
              echo "Calling Set Config File ..."
            displayName: "Set Config File"

          - bash: |
              echo "Calling Deploy ..."
            displayName: "Deploy"
