# release-integration.yml
parameters:
  - name: teamIdentifier
    type: string
    default: ""
  - name: appName
    type: string
    default: ""
  - name: targetRegion
    type: string
    default: ""
  - name: artifactVersion
    type: string
    default: ""
  - name: ghRepoUri
    type: string
    default: ""
  - name: skipStage
    type: boolean
    default: false

stages:
  - stage: release_ring_0
    displayName: 🚀 Release ${{ parameters.targetRegion }} Environment
    dependsOn: ["init"]
    condition: |
      and(
        eq(dependencies.init.result, 'Succeeded'),
        eq('${{ parameters.skipStage }}', 'false'),
        ne('${{ parameters.targetRegion }}', ''),
        ne('${{ parameters.teamIdentifier }}', ''),
        ne('${{ parameters.appName }}', ''),
        ne('${{ parameters.artifactVersion }}', ''),
        ne('${{ parameters.ghRepoUri }}', '')
      )
    pool:
      name: "Azure Pipelines"
      vmImage: "ubuntu-latest"
    jobs:
      - job: Gitops_Deploy
        steps:
          - checkout: self
          - bash: |
              echo "Calling Set Config File ..."
            displayName: "Set Config File"
          - bash: |
              echo "Calling Deploy ..."
            displayName: "Deploy"
